# Generated by Django 3.2.9 on 2022-01-13 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20220113_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='available_count',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='availablity',
            field=models.BooleanField(default=True),
        ),
    ]
