# Generated by Django 3.2.9 on 2022-01-13 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20220114_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
