# Generated by Django 3.2.9 on 2022-01-22 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_alter_customuser_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.store'),
        ),
    ]
